apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.client.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.client.fullname" . }}
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: {{ template "elasticsearch.name" . }}
    component: "{{ .Values.master.name }}"
    release: {{ .Release.Name }}
  ports:
     - namme: http
       port: 9200
  publishNotReadyAddresses: true
